=head1 NAME

kvmadm - Manage KVMs under SMF control

=head1 SYNOPSIS

B<kvmadm> I<command> [I<options...>]

where 'command' is one of the following:

    create [-f <filename>] <kvm_name>

    delete <kvm_name>

    edit <kvm_name>

    list [kvm_name]

    help

    man

=head1 DESCRIPTION

Use kvmadm to create/edit your KVMs under SMF control

=head2 B<create>

creates a KVM instance with the name B<kvm_name>. Create will open an editor
where the properties can be set. zvols and/or vnics which do not
exist will be created.

for the KVM instance the following properties can be set:

 mandatory
    vnc

 optional
     vcpus
     ram
     time_base
     boot_order
     hpet
     usb_tablet
     shutdown
     cleanup

for each disk the following properties can be set:

 mandatory
     model
     disk_path
     index 

 optional
     boot
     media
     disk_size
     cache

for each vnic the following properties can be set:

 mandatory
    model
    nic_name
    index

 optional
    over
    txtimer
    txburst

for each serial the following properties can be set:

 mandatory
    serial_name
    index

=head2 B<delete>

deletes the KVM instance with the name B<kvm_name>. Note: zvols and vnics will
B<not> be deleted.

=head2 B<edit>

modify the configuration of a KVM instance. See the descriptions in the B<create>
function for details.

=head2 B<list>

lists the available KVM instances with their properties. Lists details for B<kvm_name>
is given.

=head1 EXAMPLES

create a KVM instance with the name 'test-kvm'

    kvmadm create test-kvm

check the KVM instance properties

    kvmadm list test-kvm

list the available KVM instances

    svcs system/kvm

copy a KVM instance

    kvmadm list test-kvm > test-kvm.json

    kvmadm create -f test-kvm.json

=head1 COPYRIGHT

Copyright (c) 2014 by OETIKER+PARTNER AG. All rights reserved.

=head1 LICENSE

This program is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option)
any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see L<http://www.gnu.org/licenses/>.

=head1 AUTHOR

S<Tobias Oetiker E<lt>tobi@oetiker.chE<gt>>
S<Dominik Hassler E<lt>hadfl@cpan.orgE<gt>>

=head1 ACKNOWLEDGMENT

While the clever configuration options and other cool ideas have been shamelessly
stolen from Joyent's vmadm, the bugs and misfeatures are all exclusive to kvmadm.

=head1 HISTORY

2014-10-03 had Initial Version

=cut
